DROP TABLE EMPRESTIMOS;
DROP TABLE ALUNOS;
DROP TABLE EXEMPLARES;
DROP TABLE LIVROS;
DROP SEQUENCE SEQ_LIVROS;
DROP SEQUENCE SEQ_EXEMPLARES;
DROP SEQUENCE SEQ_EMPRESTIMOS;

CREATE TABLE ALUNOS (
    REGISTRO NUMBER(8) NOT NULL PRIMARY KEY,
    NOME VARCHAR2(200) NOT NULL,
    RETIRADAS NUMBER(10) NOT NULL,
    DEVOLUCOES NUMBER(10) NOT NULL,
    CLASSIFICACOES VARCHAR2(50) NOT NULL
);

CREATE TABLE LIVROS (
    COD_LIVRO NUMBER(10) NOT NULL PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL,
    AUTOR VARCHAR2(100) NOT NULL,
    ANO_PUB NUMBER(4) NOT NULL,
    CATEGORIA VARCHAR2(100) NOT NULL
);

CREATE TABLE EXEMPLARES (
    COD_EXEMPLAR NUMBER(10) NOT NULL PRIMARY KEY,
    QUANTIDADE NUMBER(10) NOT NULL,
    CODIGO_LIVRO NUMBER(10) NOT NULL,
    CONSTRAINT FK_PAR_CODIGO_LIVRO FOREIGN KEY (CODIGO_LIVRO)
    REFERENCES LIVROS(COD_LIVRO)
);

CREATE TABLE EMPRESTIMOS (
    ID_EMPRSTIMO NUMBER(10) NOT NULL PRIMARY KEY,
    RA_ALUNO NUMBER(8) NOT NULL,
    CODIGO_EXEMPLAR NUMBER(10) NOT NULL,
    DATA_RETIRADA DATE DEFAULT SYSDATE,
    DATA_DEVOLUCAO DATE,
    CONSTRAINT FK_PAR_RA_ALUNO FOREIGN KEY (RA_ALUNO)
    REFERENCES ALUNOS(REGISTRO),
    CONSTRAINT FK_PAR_CODIGO_EXEMPLAR FOREIGN KEY (CODIGO_EXEMPLAR)
    REFERENCES EXEMPLARES(COD_EXEMPLAR)
);


CREATE SEQUENCE SEQ_LIVROS
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_EXEMPLARES
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_EMPRESTIMOS
START WITH 1
INCREMENT BY 1;



